-- Seed geo.country with ISO 3166-1 countries
-- Generated for PFE ANETI: labels FR / EN / AR + ISO2 / ISO3 / numeric code + optional currency/phone/language when available.
-- Non destructive: existing rows are updated by iso2, new rows are inserted.

BEGIN;

CREATE UNIQUE INDEX IF NOT EXISTS ux_geo_country_iso2 ON geo.country (iso2);

INSERT INTO geo.country (
    iso2, iso3, numeric_code,
    name_fr, name_en, name_ar,
    default_language_code, phone_prefix, currency_code,
    active, metadata_json
) VALUES
    ('AD', 'AND', '020', 'Andorre', 'Andorra', 'أندورا', 'ca', '+376', 'EUR', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('AE', 'ARE', '784', 'Émirats arabes unis', 'United Arab Emirates', 'الإمارات العربية المتحدة', 'ar', '+971', 'AED', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('AF', 'AFG', '004', 'Afghanistan', 'Afghanistan', 'أفغانستان', 'ps', '+93', 'AFN', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('AG', 'ATG', '028', 'Antigua-et-Barbuda', 'Antigua & Barbuda', 'أنتيغوا وبربودا', 'en', '+1268', 'XCD', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('AI', 'AIA', '660', 'Anguilla', 'Anguilla', 'أنغويلا', 'en', '+1264', 'XCD', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('AL', 'ALB', '008', 'Albanie', 'Albania', 'ألبانيا', 'sq', '+355', 'ALL', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('AM', 'ARM', '051', 'Arménie', 'Armenia', 'أرمينيا', 'hy', '+374', 'AMD', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('AO', 'AGO', '024', 'Angola', 'Angola', 'أنغولا', 'pt', '+244', 'AOA', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('AQ', 'ATA', '010', 'Antarctique', 'Antarctica', 'أنتاركتيكا', NULL, NULL, NULL, TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('AR', 'ARG', '032', 'Argentine', 'Argentina', 'الأرجنتين', 'es', '+54', 'ARS', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('AS', 'ASM', '016', 'Samoa américaines', 'American Samoa', 'ساموا الأمريكية', 'en', '+1684', 'USD', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('AT', 'AUT', '040', 'Autriche', 'Austria', 'النمسا', 'de', '+43', 'EUR', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('AU', 'AUS', '036', 'Australie', 'Australia', 'أستراليا', 'en', '+61', 'AUD', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('AW', 'ABW', '533', 'Aruba', 'Aruba', 'أروبا', 'nl', '+297', 'AWG', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('AX', 'ALA', '248', 'Îles Åland', 'Åland Islands', 'جزر آلاند', 'sv', '+358', 'EUR', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('AZ', 'AZE', '031', 'Azerbaïdjan', 'Azerbaijan', 'أذربيجان', 'az', '+994', 'AZN', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('BA', 'BIH', '070', 'Bosnie-Herzégovine', 'Bosnia & Herzegovina', 'البوسنة والهرسك', 'bs', '+387', 'BAM', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('BB', 'BRB', '052', 'Barbade', 'Barbados', 'بربادوس', 'en', '+1246', 'BBD', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('BD', 'BGD', '050', 'Bangladesh', 'Bangladesh', 'بنغلاديش', 'bn', '+880', 'BDT', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('BE', 'BEL', '056', 'Belgique', 'Belgium', 'بلجيكا', 'nl', '+32', 'EUR', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('BF', 'BFA', '854', 'Burkina Faso', 'Burkina Faso', 'بوركينا فاسو', 'fr', '+226', 'XOF', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('BG', 'BGR', '100', 'Bulgarie', 'Bulgaria', 'بلغاريا', 'bg', '+359', 'BGN', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('BH', 'BHR', '048', 'Bahreïn', 'Bahrain', 'البحرين', 'ar', '+973', 'BHD', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('BI', 'BDI', '108', 'Burundi', 'Burundi', 'بوروندي', 'fr', '+257', 'BIF', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('BJ', 'BEN', '204', 'Bénin', 'Benin', 'بنين', 'fr', '+229', 'XOF', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('BL', 'BLM', '652', 'Saint-Barthélemy', 'St. Barthélemy', 'سان بارتليمي', 'fr', '+590', 'EUR', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('BM', 'BMU', '060', 'Bermudes', 'Bermuda', 'برمودا', 'en', '+1441', 'BMD', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('BN', 'BRN', '096', 'Brunei', 'Brunei', 'بروناي', 'ms', '+673', 'BND', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('BO', 'BOL', '068', 'Bolivie', 'Bolivia', 'بوليفيا', 'es', '+591', 'BOB', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('BQ', 'BES', '535', 'Pays-Bas caribéens', 'Caribbean Netherlands', 'هولندا الكاريبية', 'nl', '+599', 'USD', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('BR', 'BRA', '076', 'Brésil', 'Brazil', 'البرازيل', 'pt', '+55', 'BRL', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('BS', 'BHS', '044', 'Bahamas', 'Bahamas', 'جزر البهاما', 'en', '+1242', 'BSD', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('BT', 'BTN', '064', 'Bhoutan', 'Bhutan', 'بوتان', 'dz', '+975', 'INR', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('BV', 'BVT', '074', 'Île Bouvet', 'Bouvet Island', 'جزيرة بوفيه', 'no', NULL, 'NOK', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('BW', 'BWA', '072', 'Botswana', 'Botswana', 'بوتسوانا', 'en', '+267', 'BWP', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('BY', 'BLR', '112', 'Biélorussie', 'Belarus', 'بيلاروس', 'be', '+375', 'BYN', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('BZ', 'BLZ', '084', 'Belize', 'Belize', 'بليز', 'en', '+501', 'BZD', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('CA', 'CAN', '124', 'Canada', 'Canada', 'كندا', 'en', '+1', 'CAD', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('CC', 'CCK', '166', 'Îles Cocos', 'Cocos (Keeling) Islands', 'جزر كوكوس (كيلينغ)', 'en', '+61', 'AUD', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('CD', 'COD', '180', 'Congo-Kinshasa', 'Congo - Kinshasa', 'الكونغو - كينشاسا', 'fr', '+243', 'CDF', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('CF', 'CAF', '140', 'République centrafricaine', 'Central African Republic', 'جمهورية أفريقيا الوسطى', 'fr', '+236', 'XAF', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('CG', 'COG', '178', 'Congo-Brazzaville', 'Congo - Brazzaville', 'الكونغو - برازافيل', 'fr', '+242', 'XAF', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('CH', 'CHE', '756', 'Suisse', 'Switzerland', 'سويسرا', 'de', '+41', 'CHF', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('CI', 'CIV', '384', 'Côte d’Ivoire', 'Côte d’Ivoire', 'ساحل العاج', 'fr', '+225', 'XOF', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('CK', 'COK', '184', 'Îles Cook', 'Cook Islands', 'جزر كوك', 'en', '+682', 'NZD', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('CL', 'CHL', '152', 'Chili', 'Chile', 'تشيلي', 'es', '+56', 'CLP', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('CM', 'CMR', '120', 'Cameroun', 'Cameroon', 'الكاميرون', 'en', '+237', 'XAF', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('CN', 'CHN', '156', 'Chine', 'China', 'الصين', 'zh', '+86', 'CNY', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('CO', 'COL', '170', 'Colombie', 'Colombia', 'كولومبيا', 'es', '+57', 'COP', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('CR', 'CRI', '188', 'Costa Rica', 'Costa Rica', 'كوستاريكا', 'es', '+506', 'CRC', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('CU', 'CUB', '192', 'Cuba', 'Cuba', 'كوبا', 'es', '+53', 'CUP', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('CV', 'CPV', '132', 'Cap-Vert', 'Cape Verde', 'الرأس الأخضر', 'pt', '+238', 'CVE', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('CW', 'CUW', '531', 'Curaçao', 'Curaçao', 'كوراساو', 'nl', '+599', 'ANG', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('CX', 'CXR', '162', 'Île Christmas', 'Christmas Island', 'جزيرة كريسماس', 'en', '+61', 'AUD', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('CY', 'CYP', '196', 'Chypre', 'Cyprus', 'قبرص', 'el', '+357', 'EUR', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('CZ', 'CZE', '203', 'Tchéquie', 'Czechia', 'التشيك', 'cs', '+420', 'CZK', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('DE', 'DEU', '276', 'Allemagne', 'Germany', 'ألمانيا', 'de', '+49', 'EUR', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('DJ', 'DJI', '262', 'Djibouti', 'Djibouti', 'جيبوتي', 'fr', '+253', 'DJF', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('DK', 'DNK', '208', 'Danemark', 'Denmark', 'الدانمرك', 'da', '+45', 'DKK', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('DM', 'DMA', '212', 'Dominique', 'Dominica', 'دومينيكا', 'en', '+1767', 'XCD', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('DO', 'DOM', '214', 'République dominicaine', 'Dominican Republic', 'جمهورية الدومينيكان', 'es', '+1809', 'DOP', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('DZ', 'DZA', '012', 'Algérie', 'Algeria', 'الجزائر', 'ar', '+213', 'DZD', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('EC', 'ECU', '218', 'Équateur', 'Ecuador', 'الإكوادور', 'es', '+593', 'USD', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('EE', 'EST', '233', 'Estonie', 'Estonia', 'إستونيا', 'et', '+372', 'EUR', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('EG', 'EGY', '818', 'Égypte', 'Egypt', 'مصر', 'ar', '+20', 'EGP', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('EH', 'ESH', '732', 'Sahara occidental', 'Western Sahara', 'الصحراء الغربية', 'es', '+212', 'MAD', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('ER', 'ERI', '232', 'Érythrée', 'Eritrea', 'إريتريا', 'ti', '+291', 'ERN', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('ES', 'ESP', '724', 'Espagne', 'Spain', 'إسبانيا', 'es', '+34', 'EUR', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('ET', 'ETH', '231', 'Éthiopie', 'Ethiopia', 'إثيوبيا', 'am', '+251', 'ETB', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('FI', 'FIN', '246', 'Finlande', 'Finland', 'فنلندا', 'fi', '+358', 'EUR', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('FJ', 'FJI', '242', 'Fidji', 'Fiji', 'فيجي', 'en', '+679', 'FJD', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('FK', 'FLK', '238', 'Îles Malouines', 'Falkland Islands', 'جزر فوكلاند', 'en', '+500', 'FKP', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('FM', 'FSM', '583', 'Micronésie', 'Micronesia', 'ميكرونيزيا', 'en', '+691', 'USD', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('FO', 'FRO', '234', 'Îles Féroé', 'Faroe Islands', 'جزر فارو', 'fo', '+298', 'DKK', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('FR', 'FRA', '250', 'France', 'France', 'فرنسا', 'fr', '+33', 'EUR', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('GA', 'GAB', '266', 'Gabon', 'Gabon', 'الغابون', 'fr', '+241', 'XAF', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('GB', 'GBR', '826', 'Royaume-Uni', 'United Kingdom', 'المملكة المتحدة', 'en', '+44', 'GBP', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('GD', 'GRD', '308', 'Grenade', 'Grenada', 'غرينادا', 'en', '+1473', 'XCD', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('GE', 'GEO', '268', 'Géorgie', 'Georgia', 'جورجيا', 'ka', '+995', 'GEL', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('GF', 'GUF', '254', 'Guyane française', 'French Guiana', 'غويانا الفرنسية', 'fr', '+594', 'EUR', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('GG', 'GGY', '831', 'Guernesey', 'Guernsey', 'غيرنزي', 'en', '+44', 'GBP', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('GH', 'GHA', '288', 'Ghana', 'Ghana', 'غانا', 'en', '+233', 'GHS', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('GI', 'GIB', '292', 'Gibraltar', 'Gibraltar', 'جبل طارق', 'en', '+350', 'GIP', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('GL', 'GRL', '304', 'Groenland', 'Greenland', 'غرينلاند', 'kl', '+299', 'DKK', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('GM', 'GMB', '270', 'Gambie', 'Gambia', 'غامبيا', 'en', '+220', 'GMD', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('GN', 'GIN', '324', 'Guinée', 'Guinea', 'غينيا', 'fr', '+224', 'GNF', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('GP', 'GLP', '312', 'Guadeloupe', 'Guadeloupe', 'غوادلوب', 'fr', '+590', 'EUR', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('GQ', 'GNQ', '226', 'Guinée équatoriale', 'Equatorial Guinea', 'غينيا الاستوائية', 'es', '+240', 'XAF', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('GR', 'GRC', '300', 'Grèce', 'Greece', 'اليونان', 'el', '+30', 'EUR', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('GS', 'SGS', '239', 'Géorgie du Sud-et-les Îles Sandwich du Sud', 'South Georgia & South Sandwich Islands', 'جورجيا الجنوبية وجزر ساندويتش الجنوبية', 'en', '+500', 'GBP', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('GT', 'GTM', '320', 'Guatemala', 'Guatemala', 'غواتيمالا', 'es', '+502', 'GTQ', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('GU', 'GUM', '316', 'Guam', 'Guam', 'غوام', 'en', '+1671', 'USD', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('GW', 'GNB', '624', 'Guinée-Bissau', 'Guinea-Bissau', 'غينيا بيساو', 'pt', '+245', 'XOF', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('GY', 'GUY', '328', 'Guyana', 'Guyana', 'غيانا', 'en', '+592', 'GYD', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('HK', 'HKG', '344', 'R.A.S. chinoise de Hong Kong', 'Hong Kong SAR China', 'هونغ كونغ الصينية (منطقة إدارية خاصة)', 'en', '+852', 'HKD', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('HM', 'HMD', '334', 'Îles Heard-et-MacDonald', 'Heard & McDonald Islands', 'جزيرة هيرد وجزر ماكدونالد', 'en', NULL, 'AUD', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('HN', 'HND', '340', 'Honduras', 'Honduras', 'هندوراس', 'es', '+504', 'HNL', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('HR', 'HRV', '191', 'Croatie', 'Croatia', 'كرواتيا', 'hr', '+385', 'EUR', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('HT', 'HTI', '332', 'Haïti', 'Haiti', 'هايتي', 'fr', '+509', 'HTG', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('HU', 'HUN', '348', 'Hongrie', 'Hungary', 'هنغاريا', 'hu', '+36', 'HUF', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('ID', 'IDN', '360', 'Indonésie', 'Indonesia', 'إندونيسيا', 'id', '+62', 'IDR', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('IE', 'IRL', '372', 'Irlande', 'Ireland', 'أيرلندا', 'ga', '+353', 'EUR', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('IL', 'ISR', '376', 'Israël', 'Israel', 'إسرائيل', 'he', '+972', 'ILS', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('IM', 'IMN', '833', 'Île de Man', 'Isle of Man', 'جزيرة مان', 'en', '+44', 'GBP', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('IN', 'IND', '356', 'Inde', 'India', 'الهند', 'hi', '+91', 'INR', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('IO', 'IOT', '086', 'Territoire britannique de l’océan Indien', 'British Indian Ocean Territory', 'الإقليم البريطاني في المحيط الهندي', 'en', '+246', 'USD', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('IQ', 'IRQ', '368', 'Irak', 'Iraq', 'العراق', 'ar', '+964', 'IQD', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('IR', 'IRN', '364', 'Iran', 'Iran', 'إيران', 'fa', '+98', 'IRR', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('IS', 'ISL', '352', 'Islande', 'Iceland', 'آيسلندا', 'is', '+354', 'ISK', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('IT', 'ITA', '380', 'Italie', 'Italy', 'إيطاليا', 'it', '+39', 'EUR', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('JE', 'JEY', '832', 'Jersey', 'Jersey', 'جيرسي', 'en', '+44', 'GBP', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('JM', 'JAM', '388', 'Jamaïque', 'Jamaica', 'جامايكا', 'en', '+1876', 'JMD', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('JO', 'JOR', '400', 'Jordanie', 'Jordan', 'الأردن', 'ar', '+962', 'JOD', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('JP', 'JPN', '392', 'Japon', 'Japan', 'اليابان', 'ja', '+81', 'JPY', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('KE', 'KEN', '404', 'Kenya', 'Kenya', 'كينيا', 'en', '+254', 'KES', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('KG', 'KGZ', '417', 'Kirghizstan', 'Kyrgyzstan', 'قيرغيزستان', 'ky', '+996', 'KGS', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('KH', 'KHM', '116', 'Cambodge', 'Cambodia', 'كمبوديا', 'km', '+855', 'KHR', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('KI', 'KIR', '296', 'Kiribati', 'Kiribati', 'كيريباتي', 'en', '+686', 'AUD', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('KM', 'COM', '174', 'Comores', 'Comoros', 'جزر القمر', 'ar', '+269', 'KMF', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('KN', 'KNA', '659', 'Saint-Christophe-et-Niévès', 'St. Kitts & Nevis', 'سانت كيتس ونيفيس', 'en', '+1869', 'XCD', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('KP', 'PRK', '408', 'Corée du Nord', 'North Korea', 'كوريا الشمالية', 'ko', '+850', 'KPW', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('KR', 'KOR', '410', 'Corée du Sud', 'South Korea', 'كوريا الجنوبية', 'ko', '+82', 'KRW', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('KW', 'KWT', '414', 'Koweït', 'Kuwait', 'الكويت', 'ar', '+965', 'KWD', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('KY', 'CYM', '136', 'Îles Caïmans', 'Cayman Islands', 'جزر كايمان', 'en', '+1345', 'KYD', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('KZ', 'KAZ', '398', 'Kazakhstan', 'Kazakhstan', 'كازاخستان', 'kk', '+76', 'KZT', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('LA', 'LAO', '418', 'Laos', 'Laos', 'لاوس', 'lo', '+856', 'LAK', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('LB', 'LBN', '422', 'Liban', 'Lebanon', 'لبنان', 'ar', '+961', 'LBP', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('LC', 'LCA', '662', 'Sainte-Lucie', 'St. Lucia', 'سانت لوسيا', 'en', '+1758', 'XCD', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('LI', 'LIE', '438', 'Liechtenstein', 'Liechtenstein', 'ليختنشتاين', 'de', '+423', 'CHF', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('LK', 'LKA', '144', 'Sri Lanka', 'Sri Lanka', 'سريلانكا', 'si', '+94', 'LKR', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('LR', 'LBR', '430', 'Liberia', 'Liberia', 'ليبيريا', 'en', '+231', 'LRD', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('LS', 'LSO', '426', 'Lesotho', 'Lesotho', 'ليسوتو', 'en', '+266', 'ZAR', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('LT', 'LTU', '440', 'Lituanie', 'Lithuania', 'ليتوانيا', 'lt', '+370', 'EUR', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('LU', 'LUX', '442', 'Luxembourg', 'Luxembourg', 'لوكسمبورغ', 'fr', '+352', 'EUR', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('LV', 'LVA', '428', 'Lettonie', 'Latvia', 'لاتفيا', 'lv', '+371', 'EUR', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('LY', 'LBY', '434', 'Libye', 'Libya', 'ليبيا', 'ar', '+218', 'LYD', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('MA', 'MAR', '504', 'Maroc', 'Morocco', 'المغرب', 'ar', '+212', 'MAD', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('MC', 'MCO', '492', 'Monaco', 'Monaco', 'موناكو', 'fr', '+377', 'EUR', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('MD', 'MDA', '498', 'Moldavie', 'Moldova', 'مولدوفا', 'ro', '+373', 'MDL', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('ME', 'MNE', '499', 'Monténégro', 'Montenegro', 'الجبل الأسود', 'sr', '+382', 'EUR', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('MF', 'MAF', '663', 'Saint-Martin', 'St. Martin', 'سان مارتن', 'fr', '+590', 'EUR', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('MG', 'MDG', '450', 'Madagascar', 'Madagascar', 'مدغشقر', 'fr', '+261', 'MGA', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('MH', 'MHL', '584', 'Îles Marshall', 'Marshall Islands', 'جزر مارشال', 'en', '+692', 'USD', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('MK', 'MKD', '807', 'Macédoine du Nord', 'North Macedonia', 'مقدونيا الشمالية', 'mk', '+389', 'MKD', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('ML', 'MLI', '466', 'Mali', 'Mali', 'مالي', 'fr', '+223', 'XOF', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('MM', 'MMR', '104', 'Myanmar (Birmanie)', 'Myanmar (Burma)', 'ميانمار (بورما)', 'my', '+95', 'MMK', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('MN', 'MNG', '496', 'Mongolie', 'Mongolia', 'منغوليا', 'mn', '+976', 'MNT', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('MO', 'MAC', '446', 'R.A.S. chinoise de Macao', 'Macao SAR China', 'منطقة ماكاو الإدارية الخاصة', 'zh', '+853', 'MOP', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('MP', 'MNP', '580', 'Îles Mariannes du Nord', 'Northern Mariana Islands', 'جزر ماريانا الشمالية', 'en', '+1670', 'USD', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('MQ', 'MTQ', '474', 'Martinique', 'Martinique', 'جزر المارتينيك', 'fr', '+596', 'EUR', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('MR', 'MRT', '478', 'Mauritanie', 'Mauritania', 'موريتانيا', 'ar', '+222', 'MRU', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('MS', 'MSR', '500', 'Montserrat', 'Montserrat', 'مونتسرات', 'en', '+1664', 'XCD', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('MT', 'MLT', '470', 'Malte', 'Malta', 'مالطا', 'mt', '+356', 'EUR', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('MU', 'MUS', '480', 'Maurice', 'Mauritius', 'موريشيوس', 'en', '+230', 'MUR', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('MV', 'MDV', '462', 'Maldives', 'Maldives', 'جزر المالديف', 'dv', '+960', 'MVR', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('MW', 'MWI', '454', 'Malawi', 'Malawi', 'ملاوي', 'en', '+265', 'MWK', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('MX', 'MEX', '484', 'Mexique', 'Mexico', 'المكسيك', 'es', '+52', 'MXN', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('MY', 'MYS', '458', 'Malaisie', 'Malaysia', 'ماليزيا', NULL, '+60', 'MYR', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('MZ', 'MOZ', '508', 'Mozambique', 'Mozambique', 'موزمبيق', 'pt', '+258', 'MZN', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('NA', 'NAM', '516', 'Namibie', 'Namibia', 'ناميبيا', 'en', '+264', 'ZAR', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('NC', 'NCL', '540', 'Nouvelle-Calédonie', 'New Caledonia', 'كاليدونيا الجديدة', 'fr', '+687', 'XPF', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('NE', 'NER', '562', 'Niger', 'Niger', 'النيجر', 'fr', '+227', 'XOF', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('NF', 'NFK', '574', 'Île Norfolk', 'Norfolk Island', 'جزيرة نورفولك', 'en', '+672', 'AUD', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('NG', 'NGA', '566', 'Nigeria', 'Nigeria', 'نيجيريا', 'en', '+234', 'NGN', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('NI', 'NIC', '558', 'Nicaragua', 'Nicaragua', 'نيكاراغوا', 'es', '+505', 'NIO', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('NL', 'NLD', '528', 'Pays-Bas', 'Netherlands', 'هولندا', 'nl', '+31', 'EUR', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('NO', 'NOR', '578', 'Norvège', 'Norway', 'النرويج', 'no', '+47', 'NOK', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('NP', 'NPL', '524', 'Népal', 'Nepal', 'نيبال', 'ne', '+977', 'NPR', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('NR', 'NRU', '520', 'Nauru', 'Nauru', 'ناورو', 'en', '+674', 'AUD', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('NU', 'NIU', '570', 'Niue', 'Niue', 'نيوي', 'en', '+683', 'NZD', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('NZ', 'NZL', '554', 'Nouvelle-Zélande', 'New Zealand', 'نيوزيلندا', 'en', '+64', 'NZD', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('OM', 'OMN', '512', 'Oman', 'Oman', 'عُمان', 'ar', '+968', 'OMR', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('PA', 'PAN', '591', 'Panama', 'Panama', 'بنما', 'es', '+507', 'PAB', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('PE', 'PER', '604', 'Pérou', 'Peru', 'بيرو', 'es', '+51', 'PEN', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('PF', 'PYF', '258', 'Polynésie française', 'French Polynesia', 'بولينيزيا الفرنسية', 'fr', '+689', 'XPF', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('PG', 'PNG', '598', 'Papouasie-Nouvelle-Guinée', 'Papua New Guinea', 'بابوا غينيا الجديدة', 'en', '+675', 'PGK', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('PH', 'PHL', '608', 'Philippines', 'Philippines', 'الفلبين', 'en', '+63', 'PHP', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('PK', 'PAK', '586', 'Pakistan', 'Pakistan', 'باكستان', 'en', '+92', 'PKR', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('PL', 'POL', '616', 'Pologne', 'Poland', 'بولندا', 'pl', '+48', 'PLN', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('PM', 'SPM', '666', 'Saint-Pierre-et-Miquelon', 'St. Pierre & Miquelon', 'سان بيير ومكويلون', 'fr', '+508', 'EUR', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('PN', 'PCN', '612', 'Îles Pitcairn', 'Pitcairn Islands', 'جزر بيتكيرن', 'en', '+64', 'NZD', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('PR', 'PRI', '630', 'Porto Rico', 'Puerto Rico', 'بورتوريكو', 'es', '+1787', 'USD', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('PS', 'PSE', '275', 'Territoires palestiniens', 'Palestinian Territories', 'الأراضي الفلسطينية', 'ar', '+970', 'ILS', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('PT', 'PRT', '620', 'Portugal', 'Portugal', 'البرتغال', 'pt', '+351', 'EUR', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('PW', 'PLW', '585', 'Palaos', 'Palau', 'بالاو', 'en', '+680', 'USD', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('PY', 'PRY', '600', 'Paraguay', 'Paraguay', 'باراغواي', 'es', '+595', 'PYG', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('QA', 'QAT', '634', 'Qatar', 'Qatar', 'قطر', 'ar', '+974', 'QAR', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('RE', 'REU', '638', 'La Réunion', 'Réunion', 'روينيون', 'fr', '+262', 'EUR', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('RO', 'ROU', '642', 'Roumanie', 'Romania', 'رومانيا', 'ro', '+40', 'RON', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('RS', 'SRB', '688', 'Serbie', 'Serbia', 'صربيا', 'sr', '+381', 'RSD', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('RU', 'RUS', '643', 'Russie', 'Russia', 'روسيا', 'ru', '+7', 'RUB', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('RW', 'RWA', '646', 'Rwanda', 'Rwanda', 'رواندا', 'rw', '+250', 'RWF', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('SA', 'SAU', '682', 'Arabie saoudite', 'Saudi Arabia', 'المملكة العربية السعودية', 'ar', '+966', 'SAR', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('SB', 'SLB', '090', 'Îles Salomon', 'Solomon Islands', 'جزر سليمان', 'en', '+677', 'SBD', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('SC', 'SYC', '690', 'Seychelles', 'Seychelles', 'سيشل', 'fr', '+248', 'SCR', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('SD', 'SDN', '729', 'Soudan', 'Sudan', 'السودان', 'ar', '+249', 'SDG', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('SE', 'SWE', '752', 'Suède', 'Sweden', 'السويد', 'sv', '+46', 'SEK', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('SG', 'SGP', '702', 'Singapour', 'Singapore', 'سنغافورة', 'en', '+65', 'SGD', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('SH', 'SHN', '654', 'Sainte-Hélène', 'St. Helena', 'سانت هيلينا', 'en', '+290', 'SHP', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('SI', 'SVN', '705', 'Slovénie', 'Slovenia', 'سلوفينيا', 'sl', '+386', 'EUR', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('SJ', 'SJM', '744', 'Svalbard et Jan Mayen', 'Svalbard & Jan Mayen', 'سفالبارد وجان ماين', 'no', '+4779', 'NOK', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('SK', 'SVK', '703', 'Slovaquie', 'Slovakia', 'سلوفاكيا', 'sk', '+421', 'EUR', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('SL', 'SLE', '694', 'Sierra Leone', 'Sierra Leone', 'سيراليون', 'en', '+232', 'SLE', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('SM', 'SMR', '674', 'Saint-Marin', 'San Marino', 'سان مارينو', 'it', '+378', 'EUR', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('SN', 'SEN', '686', 'Sénégal', 'Senegal', 'السنغال', 'fr', '+221', 'XOF', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('SO', 'SOM', '706', 'Somalie', 'Somalia', 'الصومال', 'so', '+252', 'SOS', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('SR', 'SUR', '740', 'Suriname', 'Suriname', 'سورينام', 'nl', '+597', 'SRD', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('SS', 'SSD', '728', 'Soudan du Sud', 'South Sudan', 'جنوب السودان', 'en', '+211', 'SSP', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('ST', 'STP', '678', 'Sao Tomé-et-Principe', 'São Tomé & Príncipe', 'ساو تومي وبرينسيبي', 'pt', '+239', 'STN', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('SV', 'SLV', '222', 'Salvador', 'El Salvador', 'السلفادور', 'es', '+503', 'USD', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('SX', 'SXM', '534', 'Saint-Martin (partie néerlandaise)', 'Sint Maarten', 'سانت مارتن', 'nl', '+1 721', 'ANG', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('SY', 'SYR', '760', 'Syrie', 'Syria', 'سوريا', 'ar', '+963', 'SYP', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('SZ', 'SWZ', '748', 'Eswatini', 'Eswatini', 'إسواتيني', 'en', '+268', 'SZL', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('TC', 'TCA', '796', 'Îles Turques-et-Caïques', 'Turks & Caicos Islands', 'جزر توركس وكايكوس', 'en', '+1 649', 'USD', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('TD', 'TCD', '148', 'Tchad', 'Chad', 'تشاد', 'fr', '+235', 'XAF', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('TF', 'ATF', '260', 'Terres australes françaises', 'French Southern Territories', 'الأقاليم الجنوبية الفرنسية', 'fr', NULL, 'EUR', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('TG', 'TGO', '768', 'Togo', 'Togo', 'توغو', 'fr', '+228', 'XOF', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('TH', 'THA', '764', 'Thaïlande', 'Thailand', 'تايلاند', 'th', '+66', 'THB', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('TJ', 'TJK', '762', 'Tadjikistan', 'Tajikistan', 'طاجيكستان', 'tg', '+992', 'TJS', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('TK', 'TKL', '772', 'Tokelau', 'Tokelau', 'توكيلاو', 'en', '+690', 'NZD', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('TL', 'TLS', '626', 'Timor oriental', 'Timor-Leste', 'تيمور - ليشتي', 'pt', '+670', 'USD', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('TM', 'TKM', '795', 'Turkménistan', 'Turkmenistan', 'تركمانستان', 'tk', '+993', 'TMT', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('TN', 'TUN', '788', 'Tunisie', 'Tunisia', 'تونس', 'ar', '+216', 'TND', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('TO', 'TON', '776', 'Tonga', 'Tonga', 'تونغا', 'en', '+676', 'TOP', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('TR', 'TUR', '792', 'Turquie', 'Türkiye', 'تركيا', 'tr', '+90', 'TRY', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('TT', 'TTO', '780', 'Trinité-et-Tobago', 'Trinidad & Tobago', 'ترينيداد وتوباغو', 'en', '+1868', 'TTD', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('TV', 'TUV', '798', 'Tuvalu', 'Tuvalu', 'توفالو', 'en', '+688', 'AUD', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('TW', 'TWN', '158', 'Taïwan', 'Taiwan', 'تايوان', 'zh', '+886', 'TWD', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('TZ', 'TZA', '834', 'Tanzanie', 'Tanzania', 'تنزانيا', 'sw', '+255', 'TZS', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('UA', 'UKR', '804', 'Ukraine', 'Ukraine', 'أوكرانيا', 'uk', '+380', 'UAH', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('UG', 'UGA', '800', 'Ouganda', 'Uganda', 'أوغندا', 'en', '+256', 'UGX', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('UM', 'UMI', '581', 'Îles mineures éloignées des États-Unis', 'U.S. Outlying Islands', 'جزر الولايات المتحدة النائية', 'en', NULL, 'USD', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('US', 'USA', '840', 'États-Unis', 'United States', 'الولايات المتحدة', 'en', '+1', 'USD', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('UY', 'URY', '858', 'Uruguay', 'Uruguay', 'أورغواي', 'es', '+598', 'UYU', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('UZ', 'UZB', '860', 'Ouzbékistan', 'Uzbekistan', 'أوزبكستان', 'uz', '+998', 'UZS', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('VA', 'VAT', '336', 'État de la Cité du Vatican', 'Vatican City', 'الفاتيكان', 'it', '+379', 'EUR', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('VC', 'VCT', '670', 'Saint-Vincent-et-les Grenadines', 'St. Vincent & Grenadines', 'سانت فنسنت وجزر غرينادين', 'en', '+1784', 'XCD', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('VE', 'VEN', '862', 'Venezuela', 'Venezuela', 'فنزويلا', 'es', '+58', 'VES', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('VG', 'VGB', '092', 'Îles Vierges britanniques', 'British Virgin Islands', 'جزر فيرجن البريطانية', 'en', '+1 284', 'USD', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('VI', 'VIR', '850', 'Îles Vierges des États-Unis', 'U.S. Virgin Islands', 'جزر فيرجن الأمريكية', 'en', '+1 340', 'USD', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('VN', 'VNM', '704', 'Viêt Nam', 'Vietnam', 'فيتنام', 'vi', '+84', 'VND', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('VU', 'VUT', '548', 'Vanuatu', 'Vanuatu', 'فانواتو', 'bi', '+678', 'VUV', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('WF', 'WLF', '876', 'Wallis-et-Futuna', 'Wallis & Futuna', 'جزر والس وفوتونا', 'fr', '+681', 'XPF', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('WS', 'WSM', '882', 'Samoa', 'Samoa', 'ساموا', 'sm', '+685', 'WST', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('YE', 'YEM', '887', 'Yémen', 'Yemen', 'اليمن', 'ar', '+967', 'YER', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('YT', 'MYT', '175', 'Mayotte', 'Mayotte', 'مايوت', 'fr', '+262', 'EUR', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('ZA', 'ZAF', '710', 'Afrique du Sud', 'South Africa', 'جنوب أفريقيا', 'af', '+27', 'ZAR', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('ZM', 'ZMB', '894', 'Zambie', 'Zambia', 'زامبيا', 'en', '+260', 'ZMW', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb),
    ('ZW', 'ZWE', '716', 'Zimbabwe', 'Zimbabwe', 'زيمبابوي', 'en', '+263', 'USD', TRUE, '{"source": "ISO_3166_1_BABEL_PYCOUNTRY", "seed": "geo_country_all", "generated_for": "PFE_ANETI"}'::jsonb)
ON CONFLICT (iso2) DO UPDATE SET
    iso3 = EXCLUDED.iso3,
    numeric_code = EXCLUDED.numeric_code,
    name_fr = EXCLUDED.name_fr,
    name_en = EXCLUDED.name_en,
    name_ar = EXCLUDED.name_ar,
    default_language_code = EXCLUDED.default_language_code,
    phone_prefix = EXCLUDED.phone_prefix,
    currency_code = EXCLUDED.currency_code,
    active = TRUE,
    metadata_json = geo.country.metadata_json || EXCLUDED.metadata_json,
    updated_at = now();

-- Optional practical addition: Kosovo is commonly used in forms with code XK, but it is not an officially assigned ISO 3166-1 country code.
-- Uncomment this block only if your business needs it.
-- INSERT INTO geo.country (iso2, iso3, numeric_code, name_fr, name_en, name_ar, default_language_code, phone_prefix, currency_code, active, metadata_json)
-- VALUES ('XK', 'XKX', NULL, 'Kosovo', 'Kosovo', 'كوسوفو', 'sq', '+383', 'EUR', TRUE, '{"source":"CUSTOM_NON_ISO","note":"Kosovo practical code XK"}'::jsonb)
-- ON CONFLICT (iso2) DO UPDATE SET name_fr = EXCLUDED.name_fr, name_en = EXCLUDED.name_en, name_ar = EXCLUDED.name_ar, phone_prefix = EXCLUDED.phone_prefix, currency_code = EXCLUDED.currency_code, updated_at = now();

COMMIT;

-- Verification:
-- SELECT COUNT(*) FROM geo.country;
-- SELECT iso2, iso3, numeric_code, name_fr, name_en, name_ar, default_language_code, phone_prefix, currency_code FROM geo.country ORDER BY name_fr;